CREATE TABLE ERRP_USER (
	EMPLOYEE_ID DECIMAL(10,0) PRIMARY KEY NOT NULL,
	USERNAME VARCHAR(100) NOT NULL,
	EMPLOYEE_NAME VARCHAR(200) NOT NULL,
	SUPERVISOR_ID DECIMAL(10,0),
	PASSWORD VARCHAR(100) NOT NULL,
	ENABLED BOOLEAN NOT NULL,
	CONSTRAINT FK_EMP_SUP FOREIGN KEY (SUPERVISOR_ID) REFERENCES ERRP_USER(EMPLOYEE_ID)
);

CREATE TABLE ROLE (
  ROLE_ID DECIMAL(3,0) NOT NULL,
  ROLE_NAME VARCHAR(45) NOT NULL,
  PRIMARY KEY (ROLE_ID)
);
 
CREATE TABLE USER_ROLE (
  EMPLOYEE_ID DECIMAL(10,0) NOT NULL,
  ROLE_ID DECIMAL(3,0) NOT NULL,
  KEY USER_FK_IDX (EMPLOYEE_ID),
  KEY ROLE_FK_IDX (ROLE_ID),
  CONSTRAINT ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID),
  CONSTRAINT USER_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES ERRP_USER(EMPLOYEE_ID)
);